// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { HandleMetadata$Type } from "./HandleMetadata";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["HandleMetadata"]: HandleMetadata$Type;
    ["@inco/lightning/src/lightning-parts/primitives/HandleMetadata.sol:HandleMetadata"]: HandleMetadata$Type;
  }

  interface ContractTypesMap {
    ["HandleMetadata"]: GetContractReturnType<HandleMetadata$Type["abi"]>;
    ["@inco/lightning/src/lightning-parts/primitives/HandleMetadata.sol:HandleMetadata"]: GetContractReturnType<HandleMetadata$Type["abi"]>;
  }
}
