// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import type { Address } from "viem";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";
import "@nomicfoundation/hardhat-viem/types";

export interface HandleMetadata$Type {
  "_format": "hh-sol-artifact-1",
  "contractName": "HandleMetadata",
  "sourceName": "@inco/lightning/src/lightning-parts/primitives/HandleMetadata.sol",
  "abi": [],
  "bytecode": "0x6080604052348015600e575f5ffd5b50603e80601a5f395ff3fe60806040525f5ffdfea264697066735822122050328dab7177d23d571da45c2109936d1f5e1fb6e12a6e803425e6291d4ad92764736f6c634300081c0033",
  "deployedBytecode": "0x60806040525f5ffdfea264697066735822122050328dab7177d23d571da45c2109936d1f5e1fb6e12a6e803425e6291d4ad92764736f6c634300081c0033",
  "linkReferences": {},
  "deployedLinkReferences": {}
}

declare module "@nomicfoundation/hardhat-viem/types" {
  export function deployContract(
    contractName: "HandleMetadata",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<HandleMetadata$Type["abi"]>>;
  export function deployContract(
    contractName: "@inco/lightning/src/lightning-parts/primitives/HandleMetadata.sol:HandleMetadata",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<HandleMetadata$Type["abi"]>>;

  export function sendDeploymentTransaction(
    contractName: "HandleMetadata",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<HandleMetadata$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;
  export function sendDeploymentTransaction(
    contractName: "@inco/lightning/src/lightning-parts/primitives/HandleMetadata.sol:HandleMetadata",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<HandleMetadata$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;

  export function getContractAt(
    contractName: "HandleMetadata",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<HandleMetadata$Type["abi"]>>;
  export function getContractAt(
    contractName: "@inco/lightning/src/lightning-parts/primitives/HandleMetadata.sol:HandleMetadata",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<HandleMetadata$Type["abi"]>>;
}
