version: '3'
services:
  anvil:
    image: ghcr.io/foundry-rs/foundry:latest
    command: anvil --host 0.0.0.0
    ports:
      - "8545:8545"
    volumes:
      - ./anvil-data:/root/.foundry

  covalidator:
    image: ghcr.io/inco-fhevm/covalidator:latest
    ports:
      - "8080:8080"
    environment:
      - RPC_URL=http://anvil:8545
      - CHAIN_ID=31337
    depends_on:
      - anvil 