// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { DecryptionHandler$Type } from "./DecryptionHandler";
import { DecryptionHandlerEip712Checker$Type } from "./DecryptionHandlerEip712Checker";
import { DecryptionHandlerStorage$Type } from "./DecryptionHandlerStorage";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["DecryptionHandler"]: DecryptionHandler$Type;
    ["DecryptionHandlerEip712Checker"]: DecryptionHandlerEip712Checker$Type;
    ["DecryptionHandlerStorage"]: DecryptionHandlerStorage$Type;
    ["@inco/lightning/src/lightning-parts/DecryptionHandler.sol:DecryptionHandler"]: DecryptionHandler$Type;
    ["@inco/lightning/src/lightning-parts/DecryptionHandler.sol:DecryptionHandlerEip712Checker"]: DecryptionHandlerEip712Checker$Type;
    ["@inco/lightning/src/lightning-parts/DecryptionHandler.sol:DecryptionHandlerStorage"]: DecryptionHandlerStorage$Type;
  }

  interface ContractTypesMap {
    ["DecryptionHandler"]: GetContractReturnType<DecryptionHandler$Type["abi"]>;
    ["DecryptionHandlerEip712Checker"]: GetContractReturnType<DecryptionHandlerEip712Checker$Type["abi"]>;
    ["DecryptionHandlerStorage"]: GetContractReturnType<DecryptionHandlerStorage$Type["abi"]>;
    ["@inco/lightning/src/lightning-parts/DecryptionHandler.sol:DecryptionHandler"]: GetContractReturnType<DecryptionHandler$Type["abi"]>;
    ["@inco/lightning/src/lightning-parts/DecryptionHandler.sol:DecryptionHandlerEip712Checker"]: GetContractReturnType<DecryptionHandlerEip712Checker$Type["abi"]>;
    ["@inco/lightning/src/lightning-parts/DecryptionHandler.sol:DecryptionHandlerStorage"]: GetContractReturnType<DecryptionHandlerStorage$Type["abi"]>;
  }
}
