// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { IncoLightning$Type } from "./IncoLightning";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["IncoLightning"]: IncoLightning$Type;
    ["@inco/lightning/src/IncoLightning.sol:IncoLightning"]: IncoLightning$Type;
  }

  interface ContractTypesMap {
    ["IncoLightning"]: GetContractReturnType<IncoLightning$Type["abi"]>;
    ["@inco/lightning/src/IncoLightning.sol:IncoLightning"]: GetContractReturnType<IncoLightning$Type["abi"]>;
  }
}
