// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { e$Type } from "./e";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["e"]: e$Type;
    ["@inco/lightning/src/Lib.sol:e"]: e$Type;
  }

  interface ContractTypesMap {
    ["e"]: GetContractReturnType<e$Type["abi"]>;
    ["@inco/lightning/src/Lib.sol:e"]: GetContractReturnType<e$Type["abi"]>;
  }
}
