// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import type { Address } from "viem";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";
import "@nomicfoundation/hardhat-viem/types";

export interface e$Type {
  "_format": "hh-sol-artifact-1",
  "contractName": "e",
  "sourceName": "@inco/lightning/src/Lib.sol",
  "abi": [],
  "bytecode": "0x60556032600b8282823980515f1a607314602657634e487b7160e01b5f525f60045260245ffd5b305f52607381538281f3fe730000000000000000000000000000000000000000301460806040525f5ffdfea2646970667358221220f0aab45baacf5e2a26a60412fcd2f1f2e2d20229ae1dfa5ecf76f88fb3e4920764736f6c634300081c0033",
  "deployedBytecode": "0x730000000000000000000000000000000000000000301460806040525f5ffdfea2646970667358221220f0aab45baacf5e2a26a60412fcd2f1f2e2d20229ae1dfa5ecf76f88fb3e4920764736f6c634300081c0033",
  "linkReferences": {},
  "deployedLinkReferences": {}
}

declare module "@nomicfoundation/hardhat-viem/types" {
  export function deployContract(
    contractName: "e",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<e$Type["abi"]>>;
  export function deployContract(
    contractName: "@inco/lightning/src/Lib.sol:e",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<e$Type["abi"]>>;

  export function sendDeploymentTransaction(
    contractName: "e",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<e$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;
  export function sendDeploymentTransaction(
    contractName: "@inco/lightning/src/Lib.sol:e",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<e$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;

  export function getContractAt(
    contractName: "e",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<e$Type["abi"]>>;
  export function getContractAt(
    contractName: "@inco/lightning/src/Lib.sol:e",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<e$Type["abi"]>>;
}
