// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { AccessControlListStorage$Type } from "./AccessControlListStorage";
import { BaseAccessControlList$Type } from "./BaseAccessControlList";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["AccessControlListStorage"]: AccessControlListStorage$Type;
    ["BaseAccessControlList"]: BaseAccessControlList$Type;
    ["@inco/lightning/src/lightning-parts/AccessControl/BaseAccessControlList.sol:AccessControlListStorage"]: AccessControlListStorage$Type;
    ["@inco/lightning/src/lightning-parts/AccessControl/BaseAccessControlList.sol:BaseAccessControlList"]: BaseAccessControlList$Type;
  }

  interface ContractTypesMap {
    ["AccessControlListStorage"]: GetContractReturnType<AccessControlListStorage$Type["abi"]>;
    ["BaseAccessControlList"]: GetContractReturnType<BaseAccessControlList$Type["abi"]>;
    ["@inco/lightning/src/lightning-parts/AccessControl/BaseAccessControlList.sol:AccessControlListStorage"]: GetContractReturnType<AccessControlListStorage$Type["abi"]>;
    ["@inco/lightning/src/lightning-parts/AccessControl/BaseAccessControlList.sol:BaseAccessControlList"]: GetContractReturnType<BaseAccessControlList$Type["abi"]>;
  }
}
