// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import type { Address } from "viem";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";
import "@nomicfoundation/hardhat-viem/types";

export interface BaseAccessControlList$Type {
  "_format": "hh-sol-artifact-1",
  "contractName": "BaseAccessControlList",
  "sourceName": "@inco/lightning/src/lightning-parts/AccessControl/BaseAccessControlList.sol",
  "abi": [
    {
      "inputs": [
        {
          "internalType": "bytes32",
          "name": "handle",
          "type": "bytes32"
        },
        {
          "internalType": "address",
          "name": "sender",
          "type": "address"
        }
      ],
      "name": "SenderNotAllowedForHandle",
      "type": "error"
    },
    {
      "inputs": [
        {
          "internalType": "bytes32",
          "name": "handle",
          "type": "bytes32"
        },
        {
          "internalType": "address",
          "name": "account",
          "type": "address"
        }
      ],
      "name": "allow",
      "outputs": [],
      "stateMutability": "nonpayable",
      "type": "function"
    },
    {
      "inputs": [
        {
          "internalType": "bytes32",
          "name": "handle",
          "type": "bytes32"
        },
        {
          "internalType": "address",
          "name": "account",
          "type": "address"
        }
      ],
      "name": "allowTransient",
      "outputs": [],
      "stateMutability": "nonpayable",
      "type": "function"
    },
    {
      "inputs": [
        {
          "internalType": "bytes32",
          "name": "handle",
          "type": "bytes32"
        },
        {
          "internalType": "address",
          "name": "account",
          "type": "address"
        }
      ],
      "name": "allowedTransient",
      "outputs": [
        {
          "internalType": "bool",
          "name": "",
          "type": "bool"
        }
      ],
      "stateMutability": "view",
      "type": "function"
    },
    {
      "inputs": [],
      "name": "cleanTransientStorage",
      "outputs": [],
      "stateMutability": "nonpayable",
      "type": "function"
    },
    {
      "inputs": [
        {
          "internalType": "bytes32",
          "name": "handle",
          "type": "bytes32"
        },
        {
          "internalType": "address",
          "name": "account",
          "type": "address"
        }
      ],
      "name": "isAllowed",
      "outputs": [
        {
          "internalType": "bool",
          "name": "",
          "type": "bool"
        }
      ],
      "stateMutability": "view",
      "type": "function"
    },
    {
      "inputs": [
        {
          "internalType": "bytes32",
          "name": "handle",
          "type": "bytes32"
        },
        {
          "internalType": "address",
          "name": "account",
          "type": "address"
        }
      ],
      "name": "persistAllowed",
      "outputs": [
        {
          "internalType": "bool",
          "name": "",
          "type": "bool"
        }
      ],
      "stateMutability": "view",
      "type": "function"
    }
  ],
  "bytecode": "0x6080604052348015600e575f5ffd5b5061036f8061001c5f395ff3fe608060405234801561000f575f5ffd5b5060043610610060575f3560e01c80631e2f86ba1461006457806335334c231461008b5780633e395cec1461009557806374b79a5a146100a857806382027b6d146100bb578063b9496b62146100ce575b5f5ffd5b610077610072366004610300565b6100e1565b604051901515815260200160405180910390f35b61009361012a565b005b6100936100a3366004610300565b610153565b6100776100b6366004610300565b6101a1565b6100776100c9366004610300565b6101f4565b6100936100dc366004610300565b610216565b5f9182527fea597c75836e9e4ed72237a0e6389c322017ee3f12368962289c35586a1d2598602090815260408084206001600160a01b0393909316845291905290205460ff1690565b5f5c5f5f5d6001908101905b8181101561014f57805c5f825d5f815d50600101610136565b5050565b61015d82336101f4565b8233909161019557604051634a995a5b60e11b815260048101929092526001600160a01b031660248201526044015b60405180910390fd5b505061014f82826102a4565b5f5f5f84846040516020016101d292919091825260601b6bffffffffffffffffffffffff1916602082015260340190565b60408051808303601f1901815291905280516020909101205c95945050505050565b5f6101ff83836101a1565b8061020f575061020f83836100e1565b9392505050565b61022082336101f4565b8233909161025357604051634a995a5b60e11b815260048101929092526001600160a01b0316602482015260440161018c565b50505f9182527fea597c75836e9e4ed72237a0e6389c322017ee3f12368962289c35586a1d2598602090815260408084206001600160a01b039390931684529190529020805460ff19166001179055565b5f82826040516020016102d392919091825260601b6bffffffffffffffffffffffff1916602082015260340190565b6040516020818303038152906040528051906020012090506001815d60015f5c0181815d805f5d50505050565b5f5f60408385031215610311575f5ffd5b8235915060208301356001600160a01b038116811461032e575f5ffd5b80915050925092905056fea2646970667358221220f9d82e3cc807514ad77c6fc7fa742ee7b3b3d7630e5ddb4adae1e5c0fbaa274764736f6c634300081c0033",
  "deployedBytecode": "0x608060405234801561000f575f5ffd5b5060043610610060575f3560e01c80631e2f86ba1461006457806335334c231461008b5780633e395cec1461009557806374b79a5a146100a857806382027b6d146100bb578063b9496b62146100ce575b5f5ffd5b610077610072366004610300565b6100e1565b604051901515815260200160405180910390f35b61009361012a565b005b6100936100a3366004610300565b610153565b6100776100b6366004610300565b6101a1565b6100776100c9366004610300565b6101f4565b6100936100dc366004610300565b610216565b5f9182527fea597c75836e9e4ed72237a0e6389c322017ee3f12368962289c35586a1d2598602090815260408084206001600160a01b0393909316845291905290205460ff1690565b5f5c5f5f5d6001908101905b8181101561014f57805c5f825d5f815d50600101610136565b5050565b61015d82336101f4565b8233909161019557604051634a995a5b60e11b815260048101929092526001600160a01b031660248201526044015b60405180910390fd5b505061014f82826102a4565b5f5f5f84846040516020016101d292919091825260601b6bffffffffffffffffffffffff1916602082015260340190565b60408051808303601f1901815291905280516020909101205c95945050505050565b5f6101ff83836101a1565b8061020f575061020f83836100e1565b9392505050565b61022082336101f4565b8233909161025357604051634a995a5b60e11b815260048101929092526001600160a01b0316602482015260440161018c565b50505f9182527fea597c75836e9e4ed72237a0e6389c322017ee3f12368962289c35586a1d2598602090815260408084206001600160a01b039390931684529190529020805460ff19166001179055565b5f82826040516020016102d392919091825260601b6bffffffffffffffffffffffff1916602082015260340190565b6040516020818303038152906040528051906020012090506001815d60015f5c0181815d805f5d50505050565b5f5f60408385031215610311575f5ffd5b8235915060208301356001600160a01b038116811461032e575f5ffd5b80915050925092905056fea2646970667358221220f9d82e3cc807514ad77c6fc7fa742ee7b3b3d7630e5ddb4adae1e5c0fbaa274764736f6c634300081c0033",
  "linkReferences": {},
  "deployedLinkReferences": {}
}

declare module "@nomicfoundation/hardhat-viem/types" {
  export function deployContract(
    contractName: "BaseAccessControlList",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<BaseAccessControlList$Type["abi"]>>;
  export function deployContract(
    contractName: "@inco/lightning/src/lightning-parts/AccessControl/BaseAccessControlList.sol:BaseAccessControlList",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<BaseAccessControlList$Type["abi"]>>;

  export function sendDeploymentTransaction(
    contractName: "BaseAccessControlList",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<BaseAccessControlList$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;
  export function sendDeploymentTransaction(
    contractName: "@inco/lightning/src/lightning-parts/AccessControl/BaseAccessControlList.sol:BaseAccessControlList",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<BaseAccessControlList$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;

  export function getContractAt(
    contractName: "BaseAccessControlList",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<BaseAccessControlList$Type["abi"]>>;
  export function getContractAt(
    contractName: "@inco/lightning/src/lightning-parts/AccessControl/BaseAccessControlList.sol:BaseAccessControlList",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<BaseAccessControlList$Type["abi"]>>;
}
