// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { TrivialEncryption$Type } from "./TrivialEncryption";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["TrivialEncryption"]: TrivialEncryption$Type;
    ["@inco/lightning/src/lightning-parts/TrivialEncryption.sol:TrivialEncryption"]: TrivialEncryption$Type;
  }

  interface ContractTypesMap {
    ["TrivialEncryption"]: GetContractReturnType<TrivialEncryption$Type["abi"]>;
    ["@inco/lightning/src/lightning-parts/TrivialEncryption.sol:TrivialEncryption"]: GetContractReturnType<TrivialEncryption$Type["abi"]>;
  }
}
