// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { EncryptedOperations$Type } from "./EncryptedOperations";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["EncryptedOperations"]: EncryptedOperations$Type;
    ["@inco/lightning/src/lightning-parts/EncryptedOperations.sol:EncryptedOperations"]: EncryptedOperations$Type;
  }

  interface ContractTypesMap {
    ["EncryptedOperations"]: GetContractReturnType<EncryptedOperations$Type["abi"]>;
    ["@inco/lightning/src/lightning-parts/EncryptedOperations.sol:EncryptedOperations"]: GetContractReturnType<EncryptedOperations$Type["abi"]>;
  }
}
