// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { HandleGeneration$Type } from "./HandleGeneration";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["HandleGeneration"]: HandleGeneration$Type;
    ["@inco/lightning/src/lightning-parts/primitives/HandleGeneration.sol:HandleGeneration"]: HandleGeneration$Type;
  }

  interface ContractTypesMap {
    ["HandleGeneration"]: GetContractReturnType<HandleGeneration$Type["abi"]>;
    ["@inco/lightning/src/lightning-parts/primitives/HandleGeneration.sol:HandleGeneration"]: GetContractReturnType<HandleGeneration$Type["abi"]>;
  }
}
