// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { SignatureVerifier$Type } from "./SignatureVerifier";
import { SignatureVerifierStorage$Type } from "./SignatureVerifierStorage";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["SignatureVerifier"]: SignatureVerifier$Type;
    ["SignatureVerifierStorage"]: SignatureVerifierStorage$Type;
    ["@inco/lightning/src/lightning-parts/primitives/SignatureVerifier.sol:SignatureVerifier"]: SignatureVerifier$Type;
    ["@inco/lightning/src/lightning-parts/primitives/SignatureVerifier.sol:SignatureVerifierStorage"]: SignatureVerifierStorage$Type;
  }

  interface ContractTypesMap {
    ["SignatureVerifier"]: GetContractReturnType<SignatureVerifier$Type["abi"]>;
    ["SignatureVerifierStorage"]: GetContractReturnType<SignatureVerifierStorage$Type["abi"]>;
    ["@inco/lightning/src/lightning-parts/primitives/SignatureVerifier.sol:SignatureVerifier"]: GetContractReturnType<SignatureVerifier$Type["abi"]>;
    ["@inco/lightning/src/lightning-parts/primitives/SignatureVerifier.sol:SignatureVerifierStorage"]: GetContractReturnType<SignatureVerifierStorage$Type["abi"]>;
  }
}
