// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import type { Address } from "viem";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";
import "@nomicfoundation/hardhat-viem/types";

export interface SignatureVerifierStorage$Type {
  "_format": "hh-sol-artifact-1",
  "contractName": "SignatureVerifierStorage",
  "sourceName": "@inco/lightning/src/lightning-parts/primitives/SignatureVerifier.sol",
  "abi": [],
  "bytecode": "0x6080604052348015600e575f5ffd5b50603e80601a5f395ff3fe60806040525f5ffdfea264697066735822122017d1f9cc6fc61988060b9e68d60350ccb2be7a71c216a079a551b2fb1b6851c464736f6c634300081c0033",
  "deployedBytecode": "0x60806040525f5ffdfea264697066735822122017d1f9cc6fc61988060b9e68d60350ccb2be7a71c216a079a551b2fb1b6851c464736f6c634300081c0033",
  "linkReferences": {},
  "deployedLinkReferences": {}
}

declare module "@nomicfoundation/hardhat-viem/types" {
  export function deployContract(
    contractName: "SignatureVerifierStorage",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<SignatureVerifierStorage$Type["abi"]>>;
  export function deployContract(
    contractName: "@inco/lightning/src/lightning-parts/primitives/SignatureVerifier.sol:SignatureVerifierStorage",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<SignatureVerifierStorage$Type["abi"]>>;

  export function sendDeploymentTransaction(
    contractName: "SignatureVerifierStorage",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<SignatureVerifierStorage$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;
  export function sendDeploymentTransaction(
    contractName: "@inco/lightning/src/lightning-parts/primitives/SignatureVerifier.sol:SignatureVerifierStorage",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<SignatureVerifierStorage$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;

  export function getContractAt(
    contractName: "SignatureVerifierStorage",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<SignatureVerifierStorage$Type["abi"]>>;
  export function getContractAt(
    contractName: "@inco/lightning/src/lightning-parts/primitives/SignatureVerifier.sol:SignatureVerifierStorage",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<SignatureVerifierStorage$Type["abi"]>>;
}
