// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { ConfidentialERC20$Type } from "./ConfidentialERC20";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["ConfidentialERC20"]: ConfidentialERC20$Type;
    ["contracts/ConfidentialERC20.sol:ConfidentialERC20"]: ConfidentialERC20$Type;
  }

  interface ContractTypesMap {
    ["ConfidentialERC20"]: GetContractReturnType<ConfidentialERC20$Type["abi"]>;
    ["contracts/ConfidentialERC20.sol:ConfidentialERC20"]: GetContractReturnType<ConfidentialERC20$Type["abi"]>;
  }
}
