// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { EventCounter$Type } from "./EventCounter";
import { EventCounterStorage$Type } from "./EventCounterStorage";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["EventCounter"]: EventCounter$Type;
    ["EventCounterStorage"]: EventCounterStorage$Type;
    ["@inco/lightning/src/lightning-parts/primitives/EventCounter.sol:EventCounter"]: EventCounter$Type;
    ["@inco/lightning/src/lightning-parts/primitives/EventCounter.sol:EventCounterStorage"]: EventCounterStorage$Type;
  }

  interface ContractTypesMap {
    ["EventCounter"]: GetContractReturnType<EventCounter$Type["abi"]>;
    ["EventCounterStorage"]: GetContractReturnType<EventCounterStorage$Type["abi"]>;
    ["@inco/lightning/src/lightning-parts/primitives/EventCounter.sol:EventCounter"]: GetContractReturnType<EventCounter$Type["abi"]>;
    ["@inco/lightning/src/lightning-parts/primitives/EventCounter.sol:EventCounterStorage"]: GetContractReturnType<EventCounterStorage$Type["abi"]>;
  }
}
