// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import type { Address } from "viem";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";
import "@nomicfoundation/hardhat-viem/types";

export interface EventCounter$Type {
  "_format": "hh-sol-artifact-1",
  "contractName": "EventCounter",
  "sourceName": "@inco/lightning/src/lightning-parts/primitives/EventCounter.sol",
  "abi": [
    {
      "inputs": [],
      "name": "getEventCounter",
      "outputs": [
        {
          "internalType": "uint256",
          "name": "",
          "type": "uint256"
        }
      ],
      "stateMutability": "view",
      "type": "function"
    }
  ],
  "bytecode": "0x6080604052348015600e575f5ffd5b50609480601a5f395ff3fe6080604052348015600e575f5ffd5b50600436106026575f3560e01c80633c82a97814602a575b5f5ffd5b7f424e67de01535191ae441dac30ebc840d30f78dda500964a3abe35b40c86270c5460405190815260200160405180910390f3fea2646970667358221220ab86686fb020918faf790eb6bab666f85d9645efa73942274ca97a247eab331c64736f6c634300081c0033",
  "deployedBytecode": "0x6080604052348015600e575f5ffd5b50600436106026575f3560e01c80633c82a97814602a575b5f5ffd5b7f424e67de01535191ae441dac30ebc840d30f78dda500964a3abe35b40c86270c5460405190815260200160405180910390f3fea2646970667358221220ab86686fb020918faf790eb6bab666f85d9645efa73942274ca97a247eab331c64736f6c634300081c0033",
  "linkReferences": {},
  "deployedLinkReferences": {}
}

declare module "@nomicfoundation/hardhat-viem/types" {
  export function deployContract(
    contractName: "EventCounter",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<EventCounter$Type["abi"]>>;
  export function deployContract(
    contractName: "@inco/lightning/src/lightning-parts/primitives/EventCounter.sol:EventCounter",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<EventCounter$Type["abi"]>>;

  export function sendDeploymentTransaction(
    contractName: "EventCounter",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<EventCounter$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;
  export function sendDeploymentTransaction(
    contractName: "@inco/lightning/src/lightning-parts/primitives/EventCounter.sol:EventCounter",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<EventCounter$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;

  export function getContractAt(
    contractName: "EventCounter",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<EventCounter$Type["abi"]>>;
  export function getContractAt(
    contractName: "@inco/lightning/src/lightning-parts/primitives/EventCounter.sol:EventCounter",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<EventCounter$Type["abi"]>>;
}
